### ISSUE TITLE
an emote for your Twitch

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [aftonsteps/rstardew#12]
Hi Afton,

I created a hexagon emote for you but posted it on my GitHub as there was no place to post it. 
I do hope you like it, as it is **a token of appreciation** of how nice you are to me (and others).

you can find your hexagon emote [here](https://github.com/PythonCoderUnicorn/R_issues/tree/main/emotes)

**Comment by aftonsteps** [comment]
Oh my gosh! Thank you!
